In [1]:
import pandas as pd
data = pd.read_csv("final_data_county.csv")
data

,Unnamed: 0,POPULATION,AGE15_19,AGE20_24,AGE25_29,AGE30_34,AGE55_59,AGE60_64,TOTAL_MALE,TOTAL_FEMALE,...,UNEMP_16-19,UNEMP_20-24,UNEMP_25-29,UNEMP_30-34,UNEMP_35-44,UNEMP_45-54,UNEMP_55-59,UNEMP_60-64,UNEMP_65-74,UNEMP_OVER75
0,0,55200.0,7.0,6.0,6.6,6.2,7.5,4.9,26874.0,28326.0,...,14.2,12.7,3.6,3.7,3.6,2.4,1.4,3.2,1.5,0.0
1,1,208107.0,6.1,5.2,5.7,5.5,6.9,7.1,101188.0,106919.0,...,13.5,9.7,8.6,2.2,2.4,4.4,1.4,2.0,3.2,2.6
2,2,25782.0,5.6,6.4,7.2,7.0,6.4,6.4,13697.0,12085.0,...,27.2,11.9,20.3,14.1,9.4,5.4,3.4,1.2,3.0,9.2
3,3,22527.0,6.7,6.6,6.9,6.7,6.6,5.4,12152.0,10375.0,...,30.0,19.1,8.8,16.8,5.0,3.7,0.6,1.9,4.5,0.0
4,4,57645.0,6.4,5.5,5.9,5.9,6.8,6.3,28434.0,29211.0,...,21.5,8.6,2.9,2.3,4.2,3.1,2.5,3.0,2.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,3216,8771.0,3.9,6.2,6.0,5.7,7.3,7.5,4332.0,4439.0,...,0.0,11.6,21.1,11.1,25.9,5.9,14.6,26.9,0.0,-
3217,3217,22993.0,8.1,7.7,6.6,5.5,8.0,5.8,11169.0,11824.0,...,64.7,56.3,33.1,20.8,11.2,11.4,13.9,4.4,0.0,0.0
3218,3218,34149.0,6.8,6.9,6.2,5.3,6.6,7.5,16541.0,17608.0,...,70.1,40.0,19.7,25.1,31.1,15.9,15.1,24.4,0.0,0.0
3219,3219,36439.0,6.5,6.3,5.9,5.4,7.8,6.2,17475.0,18964.0,...,56.3,44.3,19.4,24.3,16.7,17.6,20.4,11.7,0.0,0.0
3220,3220,322903030.0,6.6,6.9,7.1,6.7,6.7,6.1,158984190.0,163918840.0,...,18.9,10.5,6.8,5.5,4.6,4.3,4.1,3.7,3.5,3.5

In [2]:
data = data.drop('Unnamed: 0', axis = 1)
data = data.drop('GEOGRAPHIC AREA NAME', axis = 1)
data

,POPULATION,AGE15_19,AGE20_24,AGE25_29,AGE30_34,AGE55_59,AGE60_64,TOTAL_MALE,TOTAL_FEMALE,GEO_ID,...,UNEMP_16-19,UNEMP_20-24,UNEMP_25-29,UNEMP_30-34,UNEMP_35-44,UNEMP_45-54,UNEMP_55-59,UNEMP_60-64,UNEMP_65-74,UNEMP_OVER75
0,55200.0,7.0,6.0,6.6,6.2,7.5,4.9,26874.0,28326.0,0500000US01001,...,14.2,12.7,3.6,3.7,3.6,2.4,1.4,3.2,1.5,0.0
1,208107.0,6.1,5.2,5.7,5.5,6.9,7.1,101188.0,106919.0,0500000US01003,...,13.5,9.7,8.6,2.2,2.4,4.4,1.4,2.0,3.2,2.6
2,25782.0,5.6,6.4,7.2,7.0,6.4,6.4,13697.0,12085.0,0500000US01005,...,27.2,11.9,20.3,14.1,9.4,5.4,3.4,1.2,3.0,9.2
3,22527.0,6.7,6.6,6.9,6.7,6.6,5.4,12152.0,10375.0,0500000US01007,...,30.0,19.1,8.8,16.8,5.0,3.7,0.6,1.9,4.5,0.0
4,57645.0,6.4,5.5,5.9,5.9,6.8,6.3,28434.0,29211.0,0500000US01009,...,21.5,8.6,2.9,2.3,4.2,3.1,2.5,3.0,2.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,8771.0,3.9,6.2,6.0,5.7,7.3,7.5,4332.0,4439.0,0500000US72147,...,0.0,11.6,21.1,11.1,25.9,5.9,14.6,26.9,0.0,-
3217,22993.0,8.1,7.7,6.6,5.5,8.0,5.8,11169.0,11824.0,0500000US72149,...,64.7,56.3,33.1,20.8,11.2,11.4,13.9,4.4,0.0,0.0
3218,34149.0,6.8,6.9,6.2,5.3,6.6,7.5,16541.0,17608.0,0500000US72151,...,70.1,40.0,19.7,25.1,31.1,15.9,15.1,24.4,0.0,0.0
3219,36439.0,6.5,6.3,5.9,5.4,7.8,6.2,17475.0,18964.0,0500000US72153,...,56.3,44.3,19.4,24.3,16.7,17.6,20.4,11.7,0.0,0.0
3220,322903030.0,6.6,6.9,7.1,6.7,6.7,6.1,158984190.0,163918840.0,0100000US,...,18.9,10.5,6.8,5.5,4.6,4.3,4.1,3.7,3.5,3.5

In [3]:
geoID = data["GEO_ID"]
county = data["COUNTY"]
state = data["STATE"]
data = data.drop(columns = ["GEO_ID", "COUNTY", "STATE"])
data.insert(0, "STATE", state)
data.insert(0, "COUNTY", county)
data.insert(0, "GEO_ID", geoID)
data

,GEO_ID,COUNTY,STATE,POPULATION,AGE15_19,AGE20_24,AGE25_29,AGE30_34,AGE55_59,AGE60_64,...,UNEMP_16-19,UNEMP_20-24,UNEMP_25-29,UNEMP_30-34,UNEMP_35-44,UNEMP_45-54,UNEMP_55-59,UNEMP_60-64,UNEMP_65-74,UNEMP_OVER75
0,0500000US01001,Autauga County,Alabama,55200.0,7.0,6.0,6.6,6.2,7.5,4.9,...,14.2,12.7,3.6,3.7,3.6,2.4,1.4,3.2,1.5,0.0
1,0500000US01003,Baldwin County,Alabama,208107.0,6.1,5.2,5.7,5.5,6.9,7.1,...,13.5,9.7,8.6,2.2,2.4,4.4,1.4,2.0,3.2,2.6
2,0500000US01005,Barbour County,Alabama,25782.0,5.6,6.4,7.2,7.0,6.4,6.4,...,27.2,11.9,20.3,14.1,9.4,5.4,3.4,1.2,3.0,9.2
3,0500000US01007,Bibb County,Alabama,22527.0,6.7,6.6,6.9,6.7,6.6,5.4,...,30.0,19.1,8.8,16.8,5.0,3.7,0.6,1.9,4.5,0.0
4,0500000US01009,Blount County,Alabama,57645.0,6.4,5.5,5.9,5.9,6.8,6.3,...,21.5,8.6,2.9,2.3,4.2,3.1,2.5,3.0,2.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,0500000US72147,Vieques Municipio,Puerto Rico,8771.0,3.9,6.2,6.0,5.7,7.3,7.5,...,0.0,11.6,21.1,11.1,25.9,5.9,14.6,26.9,0.0,-
3217,0500000US72149,Villalba Municipio,Puerto Rico,22993.0,8.1,7.7,6.6,5.5,8.0,5.8,...,64.7,56.3,33.1,20.8,11.2,11.4,13.9,4.4,0.0,0.0
3218,0500000US72151,Yabucoa Municipio,Puerto Rico,34149.0,6.8,6.9,6.2,5.3,6.6,7.5,...,70.1,40.0,19.7,25.1,31.1,15.9,15.1,24.4,0.0,0.0
3219,0500000US72153,Yauco Municipio,Puerto Rico,36439.0,6.5,6.3,5.9,5.4,7.8,6.2,...,56.3,44.3,19.4,24.3,16.7,17.6,20.4,11.7,0.0,0.0
3220,0100000US,United States,United States,322903030.0,6.6,6.9,7.1,6.7,6.7,6.1,...,18.9,10.5,6.8,5.5,4.6,4.3,4.1,3.7,3.5,3.5

In [4]:
data = data[data.STATE != ' Puerto Rico']
data = data[data.STATE != 'United States']
data

,GEO_ID,COUNTY,STATE,POPULATION,AGE15_19,AGE20_24,AGE25_29,AGE30_34,AGE55_59,AGE60_64,...,UNEMP_16-19,UNEMP_20-24,UNEMP_25-29,UNEMP_30-34,UNEMP_35-44,UNEMP_45-54,UNEMP_55-59,UNEMP_60-64,UNEMP_65-74,UNEMP_OVER75
0,0500000US01001,Autauga County,Alabama,55200.0,7.0,6.0,6.6,6.2,7.5,4.9,...,14.2,12.7,3.6,3.7,3.6,2.4,1.4,3.2,1.5,0.0
1,0500000US01003,Baldwin County,Alabama,208107.0,6.1,5.2,5.7,5.5,6.9,7.1,...,13.5,9.7,8.6,2.2,2.4,4.4,1.4,2.0,3.2,2.6
2,0500000US01005,Barbour County,Alabama,25782.0,5.6,6.4,7.2,7.0,6.4,6.4,...,27.2,11.9,20.3,14.1,9.4,5.4,3.4,1.2,3.0,9.2
3,0500000US01007,Bibb County,Alabama,22527.0,6.7,6.6,6.9,6.7,6.6,5.4,...,30.0,19.1,8.8,16.8,5.0,3.7,0.6,1.9,4.5,0.0
4,0500000US01009,Blount County,Alabama,57645.0,6.4,5.5,5.9,5.9,6.8,6.3,...,21.5,8.6,2.9,2.3,4.2,3.1,2.5,3.0,2.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,0500000US56037,Sweetwater County,Wyoming,44117.0,7.2,6.2,7.1,7.7,7.0,6.1,...,17.3,5.2,7.1,4.8,3.8,4.2,5.5,2.2,3.3,0.0
3138,0500000US56039,Teton County,Wyoming,23059.0,4.0,4.8,9.3,9.1,6.4,6.6,...,3.2,2.2,2.3,3.0,0.0,0.8,0.0,0.2,5.9,0.0
3139,0500000US56041,Uinta County,Wyoming,20609.0,7.2,5.5,5.4,6.5,8.5,5.7,...,11.1,13.6,9.4,2.1,9.7,1.3,1.2,0.2,10.6,15.2
3140,0500000US56043,Washakie County,Wyoming,8129.0,7.1,5.0,4.6,5.0,7.1,7.5,...,1.4,3.2,8.6,1.9,3.8,9.1,11.2,7.4,4.8,0.0
3141,0500000US56045,Weston County,Wyoming,7100.0,4.5,6.7,5.1,6.0,5.3,11.4,...,8.4,7.0,6.5,7.5,2.7,3.0,0.0,1.8,0.0,0.0

In [1]:
pd.DataFrame(y_proba)

NameError: name 'pd' is not defined

In [5]:
data.to_csv(r'final_census_data.csv', index = True)